# -*- coding: utf-8 -*-
"""
Created on Sat Feb 27 17:34:42 2021

@author: iremdogan
"""

ACCESS_TOKEN = "YOUR_ACCESS_TOKEN_KEY"
ACCESS_TOKEN_SECRET = "YOUR_ACCESS_TOKEN_SECRET_KEY"
CONSUMER_KEY = "YOUR_CONSUMER_KEY"
CONSUMER_SECRET = "YOUR_CONSUMER_SECRET_KEY"